### ISSUE TITLE
support multiple ptp domain or instances

### ISSUE THREAD

**Issue by zshi-redhat** [zshi-redhat/ptp#4]

**Comment by zenghui-shi** [comment]
this issue has been resolved by following commits:

commit 1cc31fc
Author: zshi <zshi@redhat.com>
Date:   Thu Jul 20 15:32:53 2017 +0800

    remove ptp4l & phc2sys service dependency

commit 1eb2ee2
Author: zshi <zshi@redhat.com>
Date:   Thu Jul 20 15:09:19 2017 +0800

    add multiple instances support in one host for ptp4l service
    1) define ptp::instance in instance.pp
    2) split ptp4l config & enabling service to separate files
    3) remove ptp4l conf parameters in ptp class

commit a5f9a35
Author: zshi <zshi@redhat.com>
Date:   Wed Jul 19 16:58:51 2017 +0800

    add multiple instance support for ptp4l service
    change conf file path and name
    
commit cf1aabc
Author: zshi <zshi@redhat.com>
Date:   Wed Jul 19 16:35:44 2017 +0800

    add multiple instance support for ptp4l service
    1) add ptp4l service profile
    2) add interface name as suffix of ptp4l conf file

commit 019c585
Author: zshi <zshi@redhat.com>
Date:   Wed Jul 19 16:35:44 2017 +0800
    add multiple instance support for ptp4l service
